# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Vc5YsV9xNQkHf3EMB07nGN1C7s68yG10
"""

import numpy as np
import pandas as pd

from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
import pickle

data = pd.read_csv("BankNoteML/BankNote_Authentication.csv")

data.head()

data.tail()

data.shape

data.isnull().sum()

data.dtypes

data.describe()

x = data.drop('class',axis=1)
y = data['class']

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=123,stratify=y)

print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

scaler = StandardScaler()
scaler.fit(x_train)

x_train = scaler.transform(x_train)
x_test = scaler.transform(x_test)

x_train.shape
x_test.shape

classifier=RandomForestClassifier()
classifier.fit(x_train,y_train)

y_pred = classifier.predict(x_test)

score = accuracy_score(y_test,y_pred)

score

pickle_out = open("BankNote.pkl","wb")
pickle.dump(classifier, pickle_out)
pickle_out.close()



